name: contancts
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
